name: test-runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setting-up:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      - name: Save Docker image
        run: |
          docker save -o app_latest.tar my-app:latest

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: app_latest.tar
          path: app_latest.tar

  run-tests:
    runs-on: windows-latest
    needs: setting-up

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Current Directory
        run: |
          "$(pwd -W)"
          ls -la

      - name: FOLDER pwd
        run: |
          echo "$(pwd -W):/app"

      - name: FOLDER github.workspace
        run: |
          echo "${{ github.workspace }}:/app"

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: app_latest.tar

      - name: Load Docker image
        run: |
          docker load -i app_latest.tar

      - name: Run tests in Docker container
        run: |
          docker run -v "$(pwd -W):/app" -i my-app npm run tests:run
          sleep 20
          ls

      - name: Upload HTML Report Files
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: /playwright-report/*.html
          retention-days: 7
