name: test-runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setting-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      - name: Run tests in Docker container
        run: |
          mv "$(pwd):/app" ${{ runner.temp }}/repo
          docker run --rm --mount type=bind, src="${{ runner.temp }}/repo", target="/data" -i my-app npm run tests:run
          sleep 5
          ls
      - name: Upload HTML Report Files
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: /playwright-report/*.html
          retention-days: 7