name: test-runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setting-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-app .

      - name: Save Docker image
        run: |
          docker save my-app | gzip > my-app.tar.gz

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: my-app.tar.gz

  run-tests:
    runs-on: ubuntu-latest
    needs: setting-up

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: my-app

      - name: Load Docker image
        run: |
          gunzip -c my-app.tar.gz | docker load

      - name: Run tests in Docker container
        run: |
          docker run --rm my-app npm run tests:run

      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: playwright-report
          retention-days: 7

      - name: Check Playwright Report
        run: |
            ls -la playwright-report